version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.code.gson:gson
    versions:
    - "> 2.8.5"
    - "< 3"
  - dependency-name: com.squareup.okhttp3:logging-interceptor
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: io.jenkins.plugins:jaxb
    versions:
    - "> 2.3.0"
    - "< 2.4"
  - dependency-name: io.jenkins.tools.bom:bom
    versions:
    - "> 2.138.1"
    - "< 3"
  - dependency-name: org.jenkins-ci.plugins:credentials
    versions:
    - ">= 2.2.a"
    - "< 2.3"
  - dependency-name: org.jenkins-ci.plugins:junit
    versions:
    - "> 1.20"
    - "< 2"
  - dependency-name: org.jenkins-ci.plugins:junit
    versions:
    - ">= 1.28.a"
    - "< 1.29"
  - dependency-name: org.jenkins-ci.plugins:Parameterized-Remote-Trigger
    versions:
    - "> 3.0.1"
    - "< 3.1"
  - dependency-name: org.jenkins-ci.plugins:Parameterized-Remote-Trigger
    versions:
    - "> 3.0.1"
    - "< 4"
  - dependency-name: org.jenkins-ci.plugins:script-security
    versions:
    - "> 1.30"
    - "< 2"
  - dependency-name: org.jenkins-ci.plugins:structs
    versions:
    - ">= 1.19.a"
    - "< 1.20"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-basic-steps
    versions:
    - ">= 2.15.a"
    - "< 2.16"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-basic-steps
    versions:
    - "> 2.4"
    - "< 3"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-cps
    versions:
    - "> 2.29"
    - "< 3"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-durable-task-step
    versions:
    - "> 2.9"
    - "< 3"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-job
    versions:
    - "> 2.10"
  - dependency-name: org.jenkins-ci.plugins.workflow:workflow-step-api
    versions:
    - "> 2.13"
